[project]
name = "coding-standards-mcp"
version = "0.1.0"
description = "MCP server for coding standards and best practices"
dependencies = [
    "mcp[cli]>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
